# ---------------------------------------------------------


indexing:
  model: 'mixedbread-ai/mxbai-embed-large-v1'


# ---------------------------------------------------------


scoring:
  crossencoder: 'mixedbread-ai/mxbai-rerank-base-v1'
  bias_detection: "d4data/bias-detection-model"


# ---------------------------------------------------------


vectordb:
  name: 'chromabd'


# ---------------------------------------------------------


relationdb:
  name: 'networkx'


# ---------------------------------------------------------