# ---------------------------------------------------------


indexing:
  model: 'BAAI/bge-small-en-v1.5'


# ---------------------------------------------------------


scoring:
  crossencoder: 'BAAI/bge-reranker-large'
  bias_detection: "d4data/bias-detection-model"


# ---------------------------------------------------------


vectordb:
  name: 'chromabd'


# ---------------------------------------------------------


relationdb:
  name: 'networkx'


# ---------------------------------------------------------