models_repo:
  path : 'C:/Users/mehul/Documents/Projects - GIT/Agents/Decompose KG from Code/pythonProject/Model'

# ---------------------------------------------------------


indexing:
  model: 'mixedbread-ai/mxbai-embed-large-v1'


# ---------------------------------------------------------


scoring:
  crossencoder: 'mixedbread-ai/mxbai-rerank-base-v1'
  bias_detection: "d4data/bias-detection-model"


# ---------------------------------------------------------


vectordb:
  name: 'chroma'
  path: 'C:\Users\mehul\Documents\Projects - GIT\Agents\Decompose KG from Code\pythonProject\CoderAssistants\tableMetadata'


# ---------------------------------------------------------


relationdb:
  name: 'networkx'


# ---------------------------------------------------------